{{- if .Values.podDisruptionBudget.enabled -}}
{{- range $component, $values := dict "api" .Values.api "web" .Values.web "validator" .Values.validator "compiler" .Values.compiler "extractor" .Values.extractor }}
{{- if and $values.enabled (gt (int $values.replicaCount) 1) }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "egide.fullname" $ }}-{{ $component }}
  labels: {{- include "egide.componentLabels" (merge (dict "component" $component) $) | nindent 4 }}
spec:
  minAvailable: {{ $.Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "egide.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: {{ $component }}
{{- end }}
{{- end }}
{{- end }}
