package ansible

import (
	"context"
	"strings"
	"testing"

	"github.com/egide/egide/services/compiler/internal/domain"
)

func sampleIntent() *domain.Intent {
	return &domain.Intent{
		ID:          "intent_db_backup_required",
		Version:     "1.0.0",
		Title:       "Production databases must have backup enabled",
		Description: "Every database flagged production-class must have backup.enabled=true and frequency_hours <= 24.",
		Selector: domain.Selector{
			Kinds: []string{"database"},
			Scope: "production",
		},
		RequiredState: []domain.RequiredStateAssertion{
			{Path: "backup.enabled", Op: domain.OpEq, Value: true},
			{Path: "backup.frequency_hours", Op: domain.OpLte, Value: 24},
		},
		ActionsOnViolation: []string{"audit", "block_deployment"},
		Severity:           domain.SeverityError,
		SourceTrace: domain.SourceTrace{
			PyramidArtifactID: "policy_data_protection_v3",
			NormativeAnchors:  []string{"iso27001-2022:A.8.13", "nis2:Art.21.2.c"},
		},
		Fixtures: domain.IntentFixtures{
			Positive: []domain.IntentFixture{
				{
					Name: "compliant prod db",
					Data: map[string]any{
						"backup": map[string]any{"enabled": true, "frequency_hours": float64(24)},
					},
					Expect: "allow",
				},
			},
			Negative: []domain.IntentFixture{
				{
					Name: "no backup",
					Data: map[string]any{
						"backup": map[string]any{"enabled": false, "frequency_hours": float64(168)},
					},
					Expect: "deny",
				},
				{
					Name: "weekly backup",
					Data: map[string]any{
						"backup": map[string]any{"enabled": true, "frequency_hours": float64(168)},
					},
					Expect: "deny",
				},
			},
		},
	}
}

func TestCompile_GeneratesValidPlaybook(t *testing.T) {
	t.Parallel()
	g := New()
	intent := sampleIntent()
	a, err := g.Compile(context.Background(), intent)
	if err != nil {
		t.Fatalf("Compile: %v", err)
	}
	if a.Target != "ansible" {
		t.Errorf("expected target=ansible, got %s", a.Target)
	}
	if a.Content == "" {
		t.Fatal("Content is empty")
	}
	mustContain := []string{
		"# Generated by Egide compiler",
		"intent_db_backup_required",
		"iso27001-2022:A.8.13",
		"nis2:Art.21.2.c",
		"hosts: production_databases",
		"tags: [audit, egide]",
		"backup.enabled == true",
		"backup.frequency_hours <= 24",
		"egide_intent_id: intent_db_backup_required",
	}
	for _, want := range mustContain {
		if !strings.Contains(a.Content, want) {
			t.Errorf("expected playbook to contain %q\n--- playbook ---\n%s\n", want, a.Content)
		}
	}
	if !strings.HasPrefix(a.ContentHash, "sha256:") {
		t.Errorf("expected sha256: prefix, got %s", a.ContentHash)
	}
}

func TestCompile_NilIntent(t *testing.T) {
	t.Parallel()
	g := New()
	if _, err := g.Compile(context.Background(), nil); err == nil {
		t.Fatal("expected error for nil intent")
	}
}

func TestTest_RunsFixtures(t *testing.T) {
	t.Parallel()
	g := New()
	intent := sampleIntent()
	a, err := g.Compile(context.Background(), intent)
	if err != nil {
		t.Fatalf("Compile: %v", err)
	}
	results, err := g.Test(context.Background(), a, intent)
	if err != nil {
		t.Fatalf("Test: %v", err)
	}
	// 1 positive + 2 negative = 3 fixture results
	if len(results) < 3 {
		t.Fatalf("expected >=3 results, got %d", len(results))
	}
	pass := 0
	for _, r := range results {
		if r.Passed {
			pass++
		}
	}
	if pass < 3 {
		t.Errorf("expected all fixtures pass, got %d/%d", pass, len(results))
	}
}

func TestCompile_EnforceMode_BlocksOnFail(t *testing.T) {
	t.Parallel()
	g := New()
	intent := sampleIntent()
	a, err := g.Compile(context.Background(), intent)
	if err != nil {
		t.Fatalf("Compile: %v", err)
	}
	// When severity=error, the playbook must include the enforcement fail task.
	if !strings.Contains(a.Content, "Egide enforcement · fail if any audit task failed") {
		t.Error("expected enforcement fail task when severity=error")
	}
}

func TestCompile_AutoRemediation(t *testing.T) {
	t.Parallel()
	g := New()
	intent := sampleIntent()
	intent.ActionsOnViolation = []string{"audit", "auto_remediate"}
	a, err := g.Compile(context.Background(), intent)
	if err != nil {
		t.Fatalf("Compile: %v", err)
	}
	if !strings.Contains(a.Content, "tags: [remediate, egide]") {
		t.Error("expected remediation tag when auto_remediate action present")
	}
	if !strings.Contains(a.Content, "apply_remediation | default(false) | bool") {
		t.Error("expected remediation gated by apply_remediation var")
	}
}
