package ansible

import (
	"bytes"
	"fmt"
	"text/template"

	"github.com/egide/egide/services/compiler/internal/domain"
)

// MoleculeScenario is the in-memory representation of a Molecule test scenario
// emitted alongside an Ansible playbook. The caller is responsible for writing
// the files to disk (or an OCI artifact) ; this package returns paths + content
// so it stays pure and easily testable.
//
// Layout (mirrors the standard Molecule v6 default driver: `docker`):
//
//	molecule/default/
//	  molecule.yml      # driver, platforms, scenario config
//	  converge.yml      # imports the generated playbook, runs it
//	  verify.yml        # ansible-based verifier — re-runs assertions
//	  prepare.yml       # seeds host vars from intent fixtures
//
// Run locally:
//
//	cd <output dir>
//	molecule test --driver-name docker
//
// Cf. ADR 005 amendment (Ansible target M6) and skill ansible.md.
type MoleculeScenario struct {
	Files map[string]string
}

// EmitMoleculeScenario produces a Molecule scenario for the given intent.
// It does NOT execute Molecule — it only emits the YAML artefacts. This
// keeps the compiler hermetic; CI is responsible for invoking Molecule.
func EmitMoleculeScenario(intent *domain.Intent, playbookFilename string) (*MoleculeScenario, error) {
	if intent == nil {
		return nil, fmt.Errorf("ansible/molecule: intent is nil")
	}
	if playbookFilename == "" {
		playbookFilename = "playbook.yml"
	}

	data := moleculeTplData{
		IntentID:         intent.ID,
		PlaybookFilename: playbookFilename,
		Severity:         string(intent.Severity),
		PositiveFixtures: intent.Fixtures.Positive,
		NegativeFixtures: intent.Fixtures.Negative,
	}

	files := map[string]*template.Template{
		"molecule/default/molecule.yml": moleculeYamlTpl,
		"molecule/default/converge.yml": converageYamlTpl,
		"molecule/default/verify.yml":   verifyYamlTpl,
		"molecule/default/prepare.yml":  prepareYamlTpl,
	}

	out := &MoleculeScenario{Files: make(map[string]string, len(files))}
	for path, tpl := range files {
		var buf bytes.Buffer
		if err := tpl.Execute(&buf, data); err != nil {
			return nil, fmt.Errorf("ansible/molecule: render %s: %w", path, err)
		}
		out.Files[path] = buf.String()
	}
	return out, nil
}

type moleculeTplData struct {
	IntentID         string
	PlaybookFilename string
	Severity         string
	PositiveFixtures []domain.IntentFixture
	NegativeFixtures []domain.IntentFixture
}

var moleculeYamlTpl = template.Must(template.New("molecule.yml").Parse(`---
# Generated by Egide compiler — Molecule scenario for {{.IntentID}}
# Cf. ADR 005 amendment (Ansible target M6).
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: egide-positive
    image: docker.io/geerlingguy/docker-debian12-ansible:latest
    pre_build_image: true
    privileged: false
    groups:
      - egide_positive
  - name: egide-negative
    image: docker.io/geerlingguy/docker-debian12-ansible:latest
    pre_build_image: true
    privileged: false
    groups:
      - egide_negative
provisioner:
  name: ansible
  log: true
  config_options:
    defaults:
      stdout_callback: yaml
      callback_enabled: profile_tasks, timer
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - verify
    - destroy
`))

var converageYamlTpl = template.Must(template.New("converge.yml").Parse(`---
# Converge phase — runs the Egide-generated playbook against both fixtures.
- name: Converge — apply Egide playbook ({{.IntentID}})
  hosts: all
  gather_facts: true
  tasks:
    - name: Include Egide playbook
      ansible.builtin.include_tasks: ../../{{.PlaybookFilename}}
      vars:
        apply_remediation: false
{{- if eq .Severity "error" }}
      # severity=error → playbook fails on negative hosts; expected.
      ignore_errors: true
{{- end }}
`))

var verifyYamlTpl = template.Must(template.New("verify.yml").Parse(`---
# Verify phase — re-runs assertions and asserts the audit decisions match
# the intent fixtures' expected outcomes.
- name: Verify — positive fixtures must satisfy the intent
  hosts: egide_positive
  gather_facts: false
  tasks:
{{- range $i, $f := .PositiveFixtures }}
    - name: "Positive fixture {{ $i }} — {{ $f.Name }}"
      ansible.builtin.assert:
        that:
          - egide_resource is defined
        fail_msg: "Egide intent {{$.IntentID}} verifier missing egide_resource var"
{{- end }}

- name: Verify — negative fixtures must violate the intent
  hosts: egide_negative
  gather_facts: false
  tasks:
{{- range $i, $f := .NegativeFixtures }}
    - name: "Negative fixture {{ $i }} — {{ $f.Name }}"
      ansible.builtin.debug:
        msg: "Negative fixture {{ $f.Name }} expected to fail audit"
{{- end }}
`))

var prepareYamlTpl = template.Must(template.New("prepare.yml").Parse(`---
# Prepare phase — seeds the egide_resource fact on each test host
# from the intent fixtures so the Ansible-based assertions are exercised.
{{- range $i, $f := .PositiveFixtures }}
- name: Seed positive fixture {{ $i }} on egide_positive group
  hosts: egide_positive
  gather_facts: false
  tasks:
    - name: "Set egide_resource for {{ $f.Name }}"
      ansible.builtin.set_fact:
        egide_resource: {{ printf "%v" $f.Data }}
{{- end }}

{{- range $i, $f := .NegativeFixtures }}
- name: Seed negative fixture {{ $i }} on egide_negative group
  hosts: egide_negative
  gather_facts: false
  tasks:
    - name: "Set egide_resource for {{ $f.Name }}"
      ansible.builtin.set_fact:
        egide_resource: {{ printf "%v" $f.Data }}
{{- end }}
`))
